# Modules/config.py
ATIVOS = {
    "Renda Fixa": [
        {"ticker": "Tesouro Selic", "nome": "Tesouro Selic 2026", "preco": 100.00, "tipo": "Tesouro", "retorno": "100% Selic"},
        {"ticker": "CDB 110%", "nome": "CDB 110% CDI", "preco": 100.00, "tipo": "CDB", "retorno": "110% CDI"},
        {"ticker": "LCI 95%", "nome": "LCI 95% CDI", "preco": 100.00, "tipo": "LCI", "retorno": "95% CDI (isento)"},
        {"ticker": "LCI 90%", "nome": "LCI 90% CDI", "preco": 100.00, "tipo": "LCI", "retorno": "90% CDI (isento)"},
        {"ticker": "CDB 100%", "nome": "CDB 100% CDI", "preco": 100.00, "tipo": "CDB", "retorno": "100% CDI"},
    ],
    "FIIs": [
        {"ticker": "MXRF11", "nome": "MXRF11 - FII Papel", "preco": 10.50, "tipo": "FII", "dy": "12% a.a."},
        {"ticker": "HGLG11", "nome": "HGLG11 - Logística", "preco": 165.00, "tipo": "FII", "dy": "8% a.a."},
        {"ticker": "KNRI11", "nome": "KNRI11 - Escritórios", "preco": 122.00, "tipo": "FII", "dy": "9% a.a."},
        {"ticker": "XPLG11", "nome": "XPLG11 - Logística", "preco": 95.00, "tipo": "FII", "dy": "10% a.a."},
        {"ticker": "CPTS11", "nome": "CPTS11 - Papel", "preco": 8.90, "tipo": "FII", "dy": "13% a.a."},
        {"ticker": "KNCR11", "nome": "KNCR11 - Papel", "preco": 95.00, "tipo": "FII", "dy": "11% a.a."},
        {"ticker": "HGBS11", "nome": "HGBS11 - Shopping", "preco": 180.00, "tipo": "FII", "dy": "7% a.a."},
        {"ticker": "VISC11", "nome": "VISC11 - Logística", "preco": 105.00, "tipo": "FII", "dy": "9% a.a."},
        {"ticker": "BRCR11", "nome": "BRCR11 - Lajes", "preco": 70.00, "tipo": "FII", "dy": "10% a.a."},
    ],
    "Ações": [
        {"ticker": "VALE3", "nome": "VALE3 - Mineração", "preco": 68.00, "tipo": "Ação", "setor": "Mineração"},
        {"ticker": "PETR4", "nome": "PETR4 - Petróleo", "preco": 37.00, "tipo": "Ação", "setor": "Energia"},
        {"ticker": "ITUB4", "nome": "ITUB4 - Banco", "preco": 32.00, "tipo": "Ação", "setor": "Financeiro"},
        {"ticker": "WEGE3", "nome": "WEGE3 - Indústria", "preco": 36.00, "tipo": "Ação", "setor": "Indústria"},
        {"ticker": "BBAS3", "nome": "BBAS3 - Banco", "preco": 48.00, "tipo": "Ação", "setor": "Financeiro"},
        {"ticker": "PRIO3", "nome": "PRIO3 - Petróleo", "preco": 42.00, "tipo": "Ação", "setor": "Energia"},
        {"ticker": "RAIZ4", "nome": "RAIZ4 - Agro", "preco": 18.00, "tipo": "Ação", "setor": "Agronegócio"},
        {"ticker": "BBDC4", "nome": "BBDC4 - Banco", "preco": 20.00, "tipo": "Ação", "setor": "Financeiro"},
        {"ticker": "ABEV3", "nome": "ABEV3 - Bebidas", "preco": 15.00, "tipo": "Ação", "setor": "Consumo"},
        {"ticker": "RENT3", "nome": "RENT3 - Locação", "preco": 55.00, "tipo": "Ação", "setor": "Serviços"},
        {"ticker": "EQTL3", "nome": "EQTL3 - Energia", "preco": 25.00, "tipo": "Ação", "setor": "Energia"},
        {"ticker": "SUZB3", "nome": "SUZB3 - Papel", "preco": 52.00, "tipo": "Ação", "setor": "Papel"},
    ],
    "ETFs Nacionais": [
        {"ticker": "IVVB11", "nome": "IVVB11 - S&P500", "preco": 280.00, "tipo": "ETF", "retorno": "S&P500"},
        {"ticker": "BOVA11", "nome": "BOVA11 - Ibovespa", "preco": 120.00, "tipo": "ETF", "retorno": "Ibovespa"},
        {"ticker": "SMAL11", "nome": "SMAL11 - Small Caps", "preco": 90.00, "tipo": "ETF", "retorno": "Small Caps"},
        {"ticker": "PIBB11", "nome": "PIBB11 - IBrX-50", "preco": 140.00, "tipo": "ETF", "retorno": "IBrX-50"},
        {"ticker": "FIXA11", "nome": "FIXA11 - Renda Fixa", "preco": 80.00, "tipo": "ETF", "retorno": "IMA-B"},
    ],
    "BDRs": [
        {"ticker": "AAPL34", "nome": "AAPL34 - Apple", "preco": 45.00, "tipo": "BDR", "setor": "Tecnologia"},
        {"ticker": "GOOGL34", "nome": "GOOGL34 - Google", "preco": 50.00, "tipo": "BDR", "setor": "Tecnologia"},
        {"ticker": "MSFT34", "nome": "MSFT34 - Microsoft", "preco": 70.00, "tipo": "BDR", "setor": "Tecnologia"},
        {"ticker": "AMZO34", "nome": "AMZO34 - Amazon", "preco": 60.00, "tipo": "BDR", "setor": "Tecnologia"},
        {"ticker": "NVDC34", "nome": "NVDC34 - NVIDIA", "preco": 80.00, "tipo": "BDR", "setor": "Tecnologia"},
        {"ticker": "MELI34", "nome": "MELI34 - Mercado Livre", "preco": 120.00, "tipo": "BDR", "setor": "Consumo"},
    ],
    "Internacional (EUA)": [
        {"ticker": "IVV", "nome": "iShares Core S&P 500 ETF", "preco": 480.00, "tipo": "ETF", "retorno": "S&P 500"},
        {"ticker": "SPY", "nome": "SPDR S&P 500 ETF", "preco": 478.00, "tipo": "ETF", "retorno": "S&P 500"},
        {"ticker": "VOO", "nome": "Vanguard S&P 500 ETF", "preco": 430.00, "tipo": "ETF", "retorno": "S&P 500"},
        {"ticker": "QQQ", "nome": "Invesco QQQ Trust", "preco": 440.00, "tipo": "ETF", "retorno": "Nasdaq-100"},
    ]
}
